### PR TITLE
Add conf files, and blacken

### PR DESCRIPTION
**Pull request by utopiabound**
Also add support for plugin being run on Ubuntu and Debian.

Signed-off-by: Nathaniel Clark <nclark@whamcloud.com>

### CODE REVIEW

**Comment by jgrund** [comment]
@utopiabound can you move the checks to github actions? travis isn't working for our repos anymore.

**Comment by utopiabound** [comment]
> @utopiabound can you move the checks to github actions? travis isn't working for our repos anymore.
As a separate patch?

**Comment by jgrund** [comment]
> As a separate patch?

yeah

**Review by ip1981 — APPROVED** [review]

**Comment by jgrund** [comment]
This now has conflicts

**Review by jgrund — APPROVED** [review]

**Pull request merged**
